In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!unzip /content/drive/MyDrive/itibi.zip -d destination_folder

Archive:  /content/drive/MyDrive/itibi.zip
  inflating: destination_folder/DelayedFlights.csv
  inflating: destination_folder/st99_d00.dbf
  inflating: destination_folder/st99_d00.shp
  inflating: destination_folder/st99_d00.shx

In [ ]:
df=pd.read_csv('/content/destination_folder/DelayedFlights.csv')

In [ ]:
df.head()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.isna().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

In [ ]:
df[df['ArrTime'].isnull()]

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
1280,1763,2008,1,3,4,922.0,915,NaN,1050,WN,...,NaN,12.0,0,N,1,NaN,NaN,NaN,NaN,NaN
1372,1911,2008,1,3,4,2325.0,1900,NaN,2030,WN,...,NaN,11.0,0,N,1,NaN,NaN,NaN,NaN,NaN
1776,2651,2008,1,4,5,1949.0,1905,NaN,1910,WN,...,NaN,11.0,0,N,1,NaN,NaN,NaN,NaN,NaN
1831,2726,2008,1,4,5,737.0,705,NaN,825,WN,...,NaN,13.0,0,N,1,NaN,NaN,NaN,NaN,NaN
2244,3672,2008,1,4,5,1849.0,1630,NaN,1755,WN,...,NaN,12.0,0,N,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1934590,7002526,2008,12,7,7,1526.0,1444,NaN,1654,DL,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
1935491,7006018,2008,12,10,3,1431.0,1422,NaN,1527,DL,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
1935651,7006289,2008,12,10,3,1459.0,1447,NaN,1650,DL,...,NaN,37.0,1,A,0,NaN,NaN,NaN,NaN,NaN
1935876,7006809,2008,12,11,4,1026.0,955,NaN,1219,DL,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
1936470,7008584,2008,12,12,5,703.0,630,NaN,734,DL,...,NaN,33.0,1,B,0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df[df['ActualElapsedTime'].isnull()]

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
1280,1763,2008,1,3,4,922.0,915,NaN,1050,WN,...,NaN,12.0,0,N,1,NaN,NaN,NaN,NaN,NaN
1372,1911,2008,1,3,4,2325.0,1900,NaN,2030,WN,...,NaN,11.0,0,N,1,NaN,NaN,NaN,NaN,NaN
1776,2651,2008,1,4,5,1949.0,1905,NaN,1910,WN,...,NaN,11.0,0,N,1,NaN,NaN,NaN,NaN,NaN
1831,2726,2008,1,4,5,737.0,705,NaN,825,WN,...,NaN,13.0,0,N,1,NaN,NaN,NaN,NaN,NaN
2244,3672,2008,1,4,5,1849.0,1630,NaN,1755,WN,...,NaN,12.0,0,N,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1935651,7006289,2008,12,10,3,1459.0,1447,NaN,1650,DL,...,NaN,37.0,1,A,0,NaN,NaN,NaN,NaN,NaN
1935716,7006401,2008,12,11,4,1355.0,1106,7.0,1950,DL,...,13.0,17.0,0,N,1,NaN,NaN,NaN,NaN,NaN
1935876,7006809,2008,12,11,4,1026.0,955,NaN,1219,DL,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
1935978,7007034,2008,12,11,4,1527.0,1520,2106.0,1708,DL,...,9.0,19.0,0,N,1,NaN,NaN,NaN,NaN,NaN
1936470,7008584,2008,12,12,5,703.0,630,NaN,734,DL,...,NaN,33.0,1,B,0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df.dropna(subset=['AirTime'])

In [ ]:
df.isna().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                   0
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   3
ActualElapsedTime         0
CRSElapsedTime            0
AirTime                   0
ArrDelay                  0
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                    0
TaxiOut                   0
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         680883
WeatherDelay         680883
NASDelay             680883
SecurityDelay        680883
LateAircraftDelay    680883
dtype: int64

In [ ]:
df.head(10)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
5,6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,...,3.0,7.0,0,N,0,10.0,0.0,0.0,0.0,47.0
6,10,2008,1,3,4,706.0,700,916.0,915,WN,...,5.0,19.0,0,N,0,NaN,NaN,NaN,NaN,NaN
7,11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,...,6.0,8.0,0,N,0,8.0,0.0,0.0,0.0,72.0
8,15,2008,1,3,4,1029.0,1020,1021.0,1010,WN,...,6.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
9,16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,...,7.0,8.0,0,N,0,3.0,0.0,0.0,0.0,12.0

In [ ]:
df['CarrierDelay'] = df['CarrierDelay'].fillna(0)

df['WeatherDelay'] = df['WeatherDelay'].fillna(0)

df['NASDelay'] = df['NASDelay'].fillna(0)

df['SecurityDelay'] = df['SecurityDelay'].fillna(0)

df['LateAircraftDelay'] = df['LateAircraftDelay'].fillna(0)

<ipython-input-16-816fdc77f41d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CarrierDelay'] = df['CarrierDelay'].fillna(0)
<ipython-input-16-816fdc77f41d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['WeatherDelay'] = df['WeatherDelay'].fillna(0)
<ipython-input-16-816fdc77f41d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NASDelay'] = df['NASDelay'].fillna(0)
<ipython-input-16-816fdc77f41d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SecurityDelay'] = df['SecurityDelay'].fillna(0)
<ipython-input-16-816fdc77f41d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['LateAircraftDelay'] = df['LateAircraftDelay'].fillna(0)

In [ ]:
df.head(10)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,0.0,0.0,0.0,0.0,0.0
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,0.0,0.0,0.0,0.0,0.0
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,0.0,0.0,0.0,0.0,0.0
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,0.0,0.0,0.0,0.0,0.0
5,6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,...,3.0,7.0,0,N,0,10.0,0.0,0.0,0.0,47.0
6,10,2008,1,3,4,706.0,700,916.0,915,WN,...,5.0,19.0,0,N,0,0.0,0.0,0.0,0.0,0.0
7,11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,...,6.0,8.0,0,N,0,8.0,0.0,0.0,0.0,72.0
8,15,2008,1,3,4,1029.0,1020,1021.0,1010,WN,...,6.0,9.0,0,N,0,0.0,0.0,0.0,0.0,0.0
9,16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,...,7.0,8.0,0,N,0,3.0,0.0,0.0,0.0,12.0

In [ ]:
df.isna().sum()

Unnamed: 0           0
Year                 0
Month                0
DayofMonth           0
DayOfWeek            0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              3
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
Cancelled            0
CancellationCode     0
Diverted             0
CarrierDelay         0
WeatherDelay         0
NASDelay             0
SecurityDelay        0
LateAircraftDelay    0
dtype: int64

In [ ]:
df = df.dropna(subset=['TailNum'])

In [ ]:
df.isna().sum()

Unnamed: 0           0
Year                 0
Month                0
DayofMonth           0
DayOfWeek            0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
Cancelled            0
CancellationCode     0
Diverted             0
CarrierDelay         0
WeatherDelay         0
NASDelay             0
SecurityDelay        0
LateAircraftDelay    0
dtype: int64

In [ ]:
df.head()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,0.0,0.0,0.0,0.0,0.0
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,0.0,0.0,0.0,0.0,0.0
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,0.0,0.0,0.0,0.0,0.0
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.to_csv('DelayedFlights.csv', index=False)